// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoK0EwDAIhlxFFoxBrQBsuzdaQ06-K0F8',
    appId: '1:893082641698:android:748ae9e838833a59aaf17b',
    messagingSenderId: '893082641698',
    projectId: 'finalchallengehailey',
    storageBucket: 'finalchallengehailey.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgCnXLT7aHr40tA473W-14-LMicrHkYtU',
    appId: '1:893082641698:ios:a0e7590a81dcf92aaaf17b',
    messagingSenderId: '893082641698',
    projectId: 'finalchallengehailey',
    storageBucket: 'finalchallengehailey.firebasestorage.app',
    iosBundleId: 'com.example.moodTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgCnXLT7aHr40tA473W-14-LMicrHkYtU',
    appId: '1:893082641698:ios:a0e7590a81dcf92aaaf17b',
    messagingSenderId: '893082641698',
    projectId: 'finalchallengehailey',
    storageBucket: 'finalchallengehailey.firebasestorage.app',
    iosBundleId: 'com.example.moodTracker',
  );

}